name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    strategy:
      matrix:
        debug: [all, debug]
    runs-on: ubuntu-latest
    container: ghcr.io/ps2homebrew/ps2homebrew:main
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add build-base git bash

      # Still compilation is not fully compatible with multi-thread
      - name: Compile project ${{ matrix.debug }}
        run: |
          unset PS2SDKSRC
          make -j $(getconf _NPROCESSORS_ONLN) clean
          make -j 1 ${{ matrix.debug }}
          make -j $(getconf _NPROCESSORS_ONLN) install
          ln -sf "$PS2SDK/ee/lib/libcglue.a" "$PS2DEV/ee/mips64r5900el-ps2-elf/lib/libcglue.a"
          ln -sf "$PS2SDK/ee/lib/libpthreadglue.a" "$PS2DEV/ee/mips64r5900el-ps2-elf/lib/libpthreadglue.a"
          ln -sf "$PS2SDK/ee/lib/libkernel.a"  "$PS2DEV/ee/mips64r5900el-ps2-elf/lib/libkernel.a"
          ln -sf "$PS2SDK/ee/lib/libcdvd.a"  "$PS2DEV/ee/mips64r5900el-ps2-elf/lib/libcdvd.a"

      - name: Compile project ${{ matrix.debug }}
        run: |
          git clone https://github.com/frno7/linux --depth 1
          cd linux/tools/r5900check
          make
          chmod +x ./r5900check
          cp ./r5900check /usr/local/bin/
          cd ../..
          rm -rf linux
          find ../ -type f \( -name "*.a" -o -name "*.irx" -o -name "*.elf" \) -print0 | xargs -0 -n 1 r5900check
          
      - name: Compile samples
        if: ${{ success() }}
        run: |
          cp -rv $PS2SDK/samples ~/
          make -C ~/samples

      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: ps2sdk-samples-${{ matrix.debug }}-${{ steps.slug.outputs.sha8 }}
          path: ~/samples
